### ISSUE TITLE
net label not flipped

### ISSUE THREAD

**Issue by EllaBarker** [xsrf/easyeda-toggleview#1]
The netlabel isn't flipped.
![easyEDa](https://user-images.githubusercontent.com/40162193/119353357-11d82080-bca3-11eb-8839-5f375253f597.JPG)

**Comment by xsrf** [comment]
thx for bringing this up, I'll have a look at it

**Comment by xsrf** [comment]
I've pushed a change to the `extension/main.js` with 1d9d39d that should flip the net names. I haven't had time to do some tests, so I won't publish an official ne version yet, but you can test it with the new `main.js`.

**Comment by EllaBarker** [comment]
Fixed the problem. 

Another one exists with the text box (<textarea id="textInputBox" class="textInputBox" [...]).
![image](https://user-images.githubusercontent.com/40162193/119889727-3c420c00-bf37-11eb-9f08-c3589f3a010b.png)

If you prefer I can open a separate issue for this.

**Comment by xsrf** [comment]
Should be fixed with 4c739f8

**Comment by xsrf** [comment]
the alignment of the box is off (it is aligned to the right end of the label) but I think that is okay... I could fix that but it would create issues when editing a text label near the left/right edge of the editor

**Comment by xsrf** [comment]
@EllaBarker I've just released the new version with both fixes
